// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8moFzWOdhNbkKf8vTjtEH4Gy9N5ez9RM',
    appId: '1:441872905402:web:102ec0334ab9c7b16bfe83',
    messagingSenderId: '441872905402',
    projectId: 'fir-28d29',
    authDomain: 'fir-28d29.firebaseapp.com',
    storageBucket: 'fir-28d29.firebasestorage.app',
    measurementId: 'G-PDYV20JQ4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkX5Y7vsp30eXtKG2qa-gtTNT5YC6u7zs',
    appId: '1:441872905402:android:ac6cd023092d49db6bfe83',
    messagingSenderId: '441872905402',
    projectId: 'fir-28d29',
    storageBucket: 'fir-28d29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPJmS7LkaRTE3mAeehzIhmNDnubUTnWU',
    appId: '1:441872905402:ios:63670ae93f86c1a06bfe83',
    messagingSenderId: '441872905402',
    projectId: 'fir-28d29',
    storageBucket: 'fir-28d29.firebasestorage.app',
    iosBundleId: 'com.example.smartBusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPJmS7LkaRTE3mAeehzIhmNDnubUTnWU',
    appId: '1:441872905402:ios:63670ae93f86c1a06bfe83',
    messagingSenderId: '441872905402',
    projectId: 'fir-28d29',
    storageBucket: 'fir-28d29.firebasestorage.app',
    iosBundleId: 'com.example.smartBusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8moFzWOdhNbkKf8vTjtEH4Gy9N5ez9RM',
    appId: '1:441872905402:web:dc35ee76cdd275a66bfe83',
    messagingSenderId: '441872905402',
    projectId: 'fir-28d29',
    authDomain: 'fir-28d29.firebaseapp.com',
    storageBucket: 'fir-28d29.firebasestorage.app',
    measurementId: 'G-YGXBV22Z0N',
  );
}
